/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControladoraBrinqueFeliz;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author Jane
 */
public class BrinqueFelizApp extends javax.swing.JFrame {

    static protected ControladoraBrinqueFeliz controle;

    /** Creates new form BrinqueFeliz */
    public BrinqueFelizApp() {
        controle = new ControladoraBrinqueFeliz();
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Iniciando componentes">
    private void initComponents() {
        this.setTitle("Brinque Feliz");

        String lookAndFeel = UIManager.getCrossPlatformLookAndFeelClassName();

        try {
            UIManager.setLookAndFeel(lookAndFeel);
        } catch (Exception e) {
        }


        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuHome = new javax.swing.JMenu();
        jMenuVenda = new javax.swing.JMenu();
        jMenuCliente = new javax.swing.JMenu();
        jMenuBrinquedo = new javax.swing.JMenu();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();
        painelCliente = new ViewCliente();
        painelRelatorio = new ViewRelatorio();
        painelBrinquedo = new ViewBrinquedo();
        painelHome = new ViewBoasVindas();
        painelVenda = new ViewVenda();



        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenuHome.setText("Home");
        jMenuHome.setName("jMenuHome"); // NOI18N
        jMenuHome.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuHomeMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuHome);

        jMenuVenda.setText("Vendas");
        jMenuVenda.setName("jMenuVenda"); // NOI18N
        jMenuVenda.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuVendaMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuVenda);

        jMenuCliente.setText("Clientes");
        jMenuCliente.setName("jMenuCliente"); // NOI18N
        jMenuCliente.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuClienteMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuCliente);

        jMenuBrinquedo.setText("Brinquedos");
        jMenuBrinquedo.setName("jMenuBrinquedo"); // NOI18N
        jMenuBrinquedo.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBrinquedoMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuBrinquedo);

        jMenuRelatorio.setText("Relatório");
        jMenuRelatorio.setName("jMenuRelatorio"); // NOI18N
        jMenuRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuRelatorioMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuRelatorio);

        jMenuSair.setText("Sair");
        jMenuSair.setName("jMenuSair"); // NOI18N
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        
        getContentPane().setLayout(layout);


//        layout.setHorizontalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 582, Short.MAX_VALUE));
//        layout.setVerticalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 470, Short.MAX_VALUE));


        painelCliente.setVisible(false);
        painelRelatorio.setVisible(false);
        painelBrinquedo.setVisible(false);
        painelHome.setVisible(true);
        painelVenda.setVisible(false);


        this.setSize(200, 100);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(painelVenda)
                .addComponent(painelHome)
                .addComponent(painelCliente)
                .addComponent(painelRelatorio)
                .addComponent(painelBrinquedo)
                                .addContainerGap(121, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addGap(31, 31, 31)
                .addComponent(painelVenda)
                .addComponent(painelHome)
                .addComponent(painelCliente)
                .addComponent(painelRelatorio)
                .addComponent(painelBrinquedo)
                .addContainerGap(137, Short.MAX_VALUE)));


        pack();
    }// </editor-fold>

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {
        int valor = 0;
        valor = JOptionPane.showConfirmDialog(null, "Fim do sistema?",
                "Finaliza sistema", JOptionPane.YES_NO_OPTION);
        if (valor == 0) {
            System.exit(0);
        }
    }

    private void jMenuHomeMouseClicked(java.awt.event.MouseEvent evt) {
        painelHome.setVisible(true);
        painelCliente.setVisible(false);
        painelBrinquedo.setVisible(false);
        painelRelatorio.setVisible(false);
        painelVenda.setVisible(false);
    }

    private void jMenuClienteMouseClicked(java.awt.event.MouseEvent evt) {
        painelHome.setVisible(false);
        painelCliente.setVisible(true);
        painelBrinquedo.setVisible(false);
        painelRelatorio.setVisible(false);
        painelVenda.setVisible(false);
    }

    private void jMenuRelatorioMouseClicked(java.awt.event.MouseEvent evt) {
        painelHome.setVisible(false);
        painelCliente.setVisible(false);
        painelBrinquedo.setVisible(false);
        painelRelatorio.setVisible(true);
        painelVenda.setVisible(false);
    }

    private void jMenuBrinquedoMouseClicked(java.awt.event.MouseEvent evt) {
        painelHome.setVisible(false);
        painelCliente.setVisible(false);
        painelBrinquedo.setVisible(true);
        painelRelatorio.setVisible(false);
        painelVenda.setVisible(false);
    }

    private void jMenuVendaMouseClicked(java.awt.event.MouseEvent evt) {
        painelHome.setVisible(false);
        painelCliente.setVisible(false);
        painelBrinquedo.setVisible(false);
        painelRelatorio.setVisible(false);
        painelVenda.setVisible(true);
    }

    static protected void mostraMensagem(String texto, String titulo) {
        JOptionPane.showMessageDialog(null, texto, titulo, JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BrinqueFelizApp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuBrinquedo;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenu jMenuRelatorio;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuVenda;
    private javax.swing.JMenu jMenuHome;
    private JPanel painelCliente;
    private JPanel painelRelatorio;
    private JPanel painelBrinquedo;
    private JPanel painelHome;
    private JPanel painelVenda;
    // End of variables declaration
}
