/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ViewVenda.java
 *
 * Created on 19/11/2010, 16:53:27
 */
package View;

import Model.Brinquedo;
import Model.Cliente;
import Model.Venda;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jane
 */
public class ViewVenda extends javax.swing.JPanel {

    /** Creates new form ViewVenda */
    public ViewVenda() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRelTitulo = new javax.swing.JLabel();
        jButtonNova = new javax.swing.JButton();
        jPanelVenda = new javax.swing.JPanel();
        jLabelData = new javax.swing.JLabel();
        jLabelCliente = new javax.swing.JLabel();
        jTextFieldCliente = new javax.swing.JTextField();
        jTextFielData = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableItens = new javax.swing.JTable();
        jButtonCliente = new javax.swing.JButton();
        jLabelValor = new javax.swing.JLabel();
        jButtonIncluir = new javax.swing.JButton();
        jButtonPagamento = new javax.swing.JButton();
        jPanelNotaFiscal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaNotaFiscal = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButtonImprimir = new javax.swing.JButton();
        jButtonFecharJanela = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabelRelTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelRelTitulo.setText("Registro de Venda");
        jLabelRelTitulo.setName("jLabelRelTitulo"); // NOI18N

        jButtonNova.setText("Nova Venda");
        jButtonNova.setName("jButtonNova"); // NOI18N
        jButtonNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovaActionPerformed(evt);
            }
        });

        jPanelVenda.setName("jPanelVenda"); // NOI18N

        jLabelData.setText("Data:");
        jLabelData.setName("jLabelData"); // NOI18N

        jLabelCliente.setText("Cliente:");
        jLabelCliente.setName("jLabelCliente"); // NOI18N

        jTextFieldCliente.setEditable(false);
        jTextFieldCliente.setName("jTextFieldCliente"); // NOI18N

        jTextFielData.setEditable(false);
        jTextFielData.setName("jTextFielData"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTableItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Descrição", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableItens.setName("jTableItens"); // NOI18N
        jTableItens.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableItensKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableItens);
        jTableItens.getColumnModel().getColumn(0).setMinWidth(40);
        jTableItens.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTableItens.getColumnModel().getColumn(0).setMaxWidth(40);
        jTableItens.getColumnModel().getColumn(0).setHeaderValue("Item");
        jTableItens.getColumnModel().getColumn(1).setHeaderValue("Descrição");
        jTableItens.getColumnModel().getColumn(2).setMinWidth(80);
        jTableItens.getColumnModel().getColumn(2).setPreferredWidth(80);
        jTableItens.getColumnModel().getColumn(2).setMaxWidth(80);
        jTableItens.getColumnModel().getColumn(2).setHeaderValue("Valor");

        jButtonCliente.setText("Seleciona");
        jButtonCliente.setName("jButtonCliente"); // NOI18N
        jButtonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClienteActionPerformed(evt);
            }
        });

        jLabelValor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelValor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelValor.setText("R$--");
        jLabelValor.setName("jLabelValor"); // NOI18N

        jButtonIncluir.setText("Incluir Item");
        jButtonIncluir.setName("jButtonIncluir"); // NOI18N
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jButtonPagamento.setText("Realizar Pagamento");
        jButtonPagamento.setName("jButtonPagamento"); // NOI18N
        jButtonPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVendaLayout = new javax.swing.GroupLayout(jPanelVenda);
        jPanelVenda.setLayout(jPanelVendaLayout);
        jPanelVendaLayout.setHorizontalGroup(
            jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendaLayout.createSequentialGroup()
                .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVendaLayout.createSequentialGroup()
                        .addComponent(jButtonIncluir)
                        .addGap(133, 133, 133)
                        .addComponent(jLabelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVendaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFielData, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVendaLayout.createSequentialGroup()
                        .addComponent(jLabelCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCliente)))
                .addContainerGap(140, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
            .addGroup(jPanelVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonPagamento)
                .addContainerGap(365, Short.MAX_VALUE))
        );
        jPanelVendaLayout.setVerticalGroup(
            jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFielData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCliente)
                    .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonIncluir)
                    .addComponent(jLabelValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPagamento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelNotaFiscal.setName("jPanelNotaFiscal"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextAreaNotaFiscal.setColumns(20);
        jTextAreaNotaFiscal.setRows(5);
        jTextAreaNotaFiscal.setName("jTextAreaNotaFiscal"); // NOI18N
        jScrollPane1.setViewportView(jTextAreaNotaFiscal);

        jLabel1.setText("Nota Fiscal:");
        jLabel1.setName("jLabel1"); // NOI18N

        jButtonImprimir.setText("Imprimir");
        jButtonImprimir.setName("jButtonImprimir"); // NOI18N

        jButtonFecharJanela.setText("Fechar Janela");
        jButtonFecharJanela.setName("jButtonFecharJanela"); // NOI18N
        jButtonFecharJanela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharJanelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNotaFiscalLayout = new javax.swing.GroupLayout(jPanelNotaFiscal);
        jPanelNotaFiscal.setLayout(jPanelNotaFiscalLayout);
        jPanelNotaFiscalLayout.setHorizontalGroup(
            jPanelNotaFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNotaFiscalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(436, Short.MAX_VALUE))
            .addGroup(jPanelNotaFiscalLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jButtonImprimir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(jButtonFecharJanela)
                .addGap(55, 55, 55))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );
        jPanelNotaFiscalLayout.setVerticalGroup(
            jPanelNotaFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNotaFiscalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNotaFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonImprimir)
                    .addComponent(jButtonFecharJanela))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                .addComponent(jButtonNova)
                .addContainerGap())
            .addComponent(jPanelVenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelNotaFiscal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNova)
                    .addComponent(jLabelRelTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovaActionPerformed
        venda = new Venda();
        jTextFielData.setText(venda.retornaData());
        jPanelVenda.setVisible(true);

        jButtonPagamento.setVisible(false);



    }//GEN-LAST:event_jButtonNovaActionPerformed

    private void jButtonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClienteActionPerformed
        String clicpf;

        clicpf = (String) JOptionPane.showInputDialog(null,
                "CPF do cliente: ", "Busca de Cliente",
                JOptionPane.QUESTION_MESSAGE, null, null, null);

        if (clicpf != null) {
            clicpf.replaceAll(" ", "");

            if (!clicpf.isEmpty()) {
                Cliente cliente = BrinqueFelizApp.controle.buscarClienteCpf(clicpf);
                if (cliente == null) {
                    BrinqueFelizApp.mostraMensagem("Cliente não cadastrado!\n "
                            + "Por favor, cancele esta venda e faça o cadastro"
                            + " do cliente", "Busca de Cliente");

                } else {

                    BrinqueFelizApp.mostraMensagem("Cliente "
                            + cliente.getNome() + " inserido na venda.",
                            "Cadastro do Cliente");
                    jTextFieldCliente.setText(cliente.getCpf() + " ("
                            + cliente.getNome() + ")");
                    venda.definirCliente(cliente);
                    jButtonIncluir.setEnabled(true);
                    jButtonIncluir.setVisible(true);
                    
                }
            }
        }


    }//GEN-LAST:event_jButtonClienteActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        jPanelVenda.setVisible(false);
        jPanelNotaFiscal.setVisible(false);

    }//GEN-LAST:event_formComponentShown

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        incluiritem();
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jTableItensKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableItensKeyPressed
        incluiritem();
    }//GEN-LAST:event_jTableItensKeyPressed

    private void jButtonPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagamentoActionPerformed
        Object[] formasPagto = {"Cheque", "Dinheiro", "Cartão Dédito", "Cartão Crédito"};
        String s = (String) JOptionPane.showInputDialog(
                null,
                "Selecione a forma de pagamento executada:",
                "Forma de pagamento",
                JOptionPane.QUESTION_MESSAGE, null,
                formasPagto,
                "Dinheiro");

        BrinqueFelizApp.controle.salvarVenda(venda);
        jPanelVenda.setVisible(false);
        jPanelNotaFiscal.setVisible(true);
        jTextAreaNotaFiscal.setText(venda.gerarNota());

    }//GEN-LAST:event_jButtonPagamentoActionPerformed

    private void jButtonFecharJanelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharJanelaActionPerformed
        jPanelNotaFiscal.setVisible(false);
    }//GEN-LAST:event_jButtonFecharJanelaActionPerformed

    private void incluiritem() {
        DefaultTableModel model = (DefaultTableModel) jTableItens.getModel();
        String cod;
        cod = (String) JOptionPane.showInputDialog(null,
                "Código de Barras: ", "Registro de item de Venda",
                JOptionPane.QUESTION_MESSAGE, null, null, null);

        if (cod != null) {
            cod.replaceAll(" ", "");

            if (!cod.isEmpty()) {
                Brinquedo brinquedo = BrinqueFelizApp.controle.buscarBrinquedoCodBarras(cod);
                if (brinquedo == null) {
                    BrinqueFelizApp.mostraMensagem("Brinquedo não cadastrado!\n "
                            + "Por favor, digite outro código de barras.",
                            "Busca de Cliente");

                } else {
                    venda.inserirItem(brinquedo);
                    model.insertRow(model.getRowCount(),
                            new Object[]{model.getRowCount() + 1,
                                brinquedo.getNome(), brinquedo.getPrecoReais()});
                    jLabelValor.setVisible(true);
                    jLabelValor.setText(venda.getTotalReais());
                    // TODO:  fazer a tabela rodar automaticamente
                    jButtonPagamento.setVisible(true);
                }
            }
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCliente;
    private javax.swing.JButton jButtonFecharJanela;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonNova;
    private javax.swing.JButton jButtonPagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelRelTitulo;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JPanel jPanelNotaFiscal;
    private javax.swing.JPanel jPanelVenda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableItens;
    private javax.swing.JTextArea jTextAreaNotaFiscal;
    private javax.swing.JTextField jTextFielData;
    private javax.swing.JTextField jTextFieldCliente;
    // End of variables declaration//GEN-END:variables
    private Venda venda;
}
