/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ViewCliente.java
 *
 * Created on 19/11/2010, 09:43:34
 */
package View;

import Model.Cliente;

/**
 *
 * @author Jane
 */
public class ViewCliente extends javax.swing.JPanel {

    /** Creates new form ViewCliente */
    public ViewCliente() {
        initComponents();
        setName("Cadastro de Clientes");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNome = new javax.swing.JTextField();
        jLabelNome = new javax.swing.JLabel();
        jLabelCpf = new javax.swing.JLabel();
        jFTextFieldCPF = new javax.swing.JFormattedTextField();
        jButtonSalvar = new javax.swing.JButton();
        jLabelRelTitulo = new javax.swing.JLabel();
        jTextFieldRg = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaEndereco = new javax.swing.JTextArea();
        jLabelRg = new javax.swing.JLabel();
        jLabelEndereco = new javax.swing.JLabel();
        jButtonLimpar = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jTextFieldNome.setName("jTextFieldNome"); // NOI18N

        jLabelNome.setText("Nome:");
        jLabelNome.setName("jLabelNome"); // NOI18N

        jLabelCpf.setText("CPF:");
        jLabelCpf.setName("jLabelCpf"); // NOI18N

        try {
            jFTextFieldCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTextFieldCPF.setName("jFTextFieldCPF"); // NOI18N

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setName("jButtonSalvar"); // NOI18N
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jLabelRelTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelRelTitulo.setText("Cadastro de Clientes");
        jLabelRelTitulo.setName("jLabelRelTitulo"); // NOI18N

        jTextFieldRg.setName("jTextFieldRg"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextAreaEndereco.setColumns(20);
        jTextAreaEndereco.setRows(3);
        jTextAreaEndereco.setName("jTextAreaEndereco"); // NOI18N
        jScrollPane1.setViewportView(jTextAreaEndereco);

        jLabelRg.setText("RG:");
        jLabelRg.setName("jLabelRg"); // NOI18N

        jLabelEndereco.setText("Endereço:");
        jLabelEndereco.setName("jLabelEndereco"); // NOI18N

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.setName("jButtonLimpar"); // NOI18N
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCpf)
                    .addComponent(jLabelNome)
                    .addComponent(jLabelRg)
                    .addComponent(jLabelEndereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                        .addComponent(jTextFieldNome))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jFTextFieldCPF, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldRg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(jButtonLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalvar)
                .addGap(256, 256, 256))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRelTitulo)
                .addContainerGap(348, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelRelTitulo)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCpf)
                    .addComponent(jFTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRg)
                    .addComponent(jTextFieldRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEndereco)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonLimpar))
                .addGap(178, 178, 178))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        String clicpf = jFTextFieldCPF.getText();
        String clinome = jTextFieldNome.getText();
        clicpf = clicpf.replace(" ", "");
        if (clicpf.length() < 14) {
            BrinqueFelizApp.mostraMensagem("CPF inválido!"
                    + "\nPreencha corretamente!", "Cadastro do Cliente");
        } else if (clinome.length() < 4) {
            BrinqueFelizApp.mostraMensagem("Nome inválido!"
                    + "\nO nome deve possui pelo menos 4 letras."
                    + "\nPreencha corretamente!", "Cadastro do Cliente");
        } else {
            Cliente cliente = BrinqueFelizApp.controle.buscarClienteCpf(clicpf);
            if (cliente == null) {

                cliente = new Cliente(clinome, clicpf);
                cliente.setRg(jTextFieldRg.getText());
                cliente.setEndereco(jTextAreaEndereco.getText());
                BrinqueFelizApp.controle.salvarCliente(cliente);
                BrinqueFelizApp.mostraMensagem("O Cliente '" + cliente.getNome() + "' "
                        + "foi cadastrado com sucesso!", "Cadastro do Cliente");
            } else {

                BrinqueFelizApp.mostraMensagem("CPF já cadastrado!", "Cadastro do Cliente");
            }

            jFTextFieldCPF.setText("");
            jTextFieldNome.setText("");
            jTextAreaEndereco.setText("");
            jTextFieldRg.setText("");
        }

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        jFTextFieldCPF.setText("");
        jTextFieldNome.setText("");
        jTextAreaEndereco.setText("");
        jTextFieldRg.setText("");
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        jFTextFieldCPF.setText("");
        jTextFieldNome.setText("");
        jTextAreaEndereco.setText("");
        jTextFieldRg.setText(""); 
    }//GEN-LAST:event_formComponentShown

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JFormattedTextField jFTextFieldCPF;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelRelTitulo;
    private javax.swing.JLabel jLabelRg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaEndereco;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldRg;
    // End of variables declaration//GEN-END:variables
}
