/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ViewRelatorio.java
 *
 * Created on 19/11/2010, 10:25:26
 */

package View;

/**
 *
 * @author Jane
 */
public class ViewRelatorio extends javax.swing.JPanel {

    /** Creates new form ViewRelatorio */
    public ViewRelatorio() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRelTitulo = new javax.swing.JLabel();
        jButtonRelatorioGerar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaRelatorio = new javax.swing.JTextArea();

        jLabelRelTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelRelTitulo.setText("Relatório Geral");
        jLabelRelTitulo.setName("jLabelRelTitulo"); // NOI18N

        jButtonRelatorioGerar.setText("Gerar Relatório");
        jButtonRelatorioGerar.setName("jButtonRelatorioGerar"); // NOI18N
        jButtonRelatorioGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioGerarActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextAreaRelatorio.setColumns(20);
        jTextAreaRelatorio.setFont(new java.awt.Font("Tahoma", 0, 12));
        jTextAreaRelatorio.setRows(5);
        jTextAreaRelatorio.setText("...");
        jTextAreaRelatorio.setName("jTextAreaRelatorio"); // NOI18N
        jScrollPane1.setViewportView(jTextAreaRelatorio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addComponent(jButtonRelatorioGerar)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonRelatorioGerar))
                    .addComponent(jLabelRelTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRelatorioGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioGerarActionPerformed
        jTextAreaRelatorio.setText(BrinqueFelizApp.controle.geraRelatorio());        
}//GEN-LAST:event_jButtonRelatorioGerarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRelatorioGerar;
    private javax.swing.JLabel jLabelRelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaRelatorio;
    // End of variables declaration//GEN-END:variables

}
